/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaanimales;

/**
 *
 * @author H ERICK
 */
public class Propietarios extends javax.swing.JFrame {

    /**
     * Creates new form Propietarios
     */
    public Propietarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrsexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblidp = new javax.swing.JLabel();
        lblnombrep = new javax.swing.JLabel();
        lblgenerop = new javax.swing.JLabel();
        lbldireccionp = new javax.swing.JLabel();
        txtidp = new javax.swing.JTextField();
        txtnombrep = new javax.swing.JTextField();
        txtdireccionp = new javax.swing.JTextField();
        btnagregar = new javax.swing.JToggleButton();
        btnmodificar = new javax.swing.JToggleButton();
        btneliminar = new javax.swing.JToggleButton();
        rbtnhombre = new javax.swing.JRadioButton();
        rbtnmujer = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("P R O P I E T A R I O S");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 210, -1));

        lblidp.setText("Id Propietario:");
        getContentPane().add(lblidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblnombrep.setText("Nombre:");
        getContentPane().add(lblnombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        lblgenerop.setText("Genero:");
        getContentPane().add(lblgenerop, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        lbldireccionp.setText("Dirección:");
        getContentPane().add(lbldireccionp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        getContentPane().add(txtidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));
        getContentPane().add(txtnombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 190, -1));
        getContentPane().add(txtdireccionp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, -1));

        btnagregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnagregar.setText("A G R E G A R");
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnmodificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnmodificar.setText("M O D I F I C A R");
        getContentPane().add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btneliminar.setText("E L I M I N A R");
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        btngrsexo.add(rbtnhombre);
        rbtnhombre.setText("Hombre");
        getContentPane().add(rbtnhombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        btngrsexo.add(rbtnmujer);
        rbtnmujer.setText("Mujer");
        getContentPane().add(rbtnmujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Propietarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Propietarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnagregar;
    private javax.swing.JToggleButton btneliminar;
    private javax.swing.ButtonGroup btngrsexo;
    private javax.swing.JToggleButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbldireccionp;
    private javax.swing.JLabel lblgenerop;
    private javax.swing.JLabel lblidp;
    private javax.swing.JLabel lblnombrep;
    private javax.swing.JRadioButton rbtnhombre;
    private javax.swing.JRadioButton rbtnmujer;
    private javax.swing.JTextField txtdireccionp;
    private javax.swing.JTextField txtidp;
    private javax.swing.JTextField txtnombrep;
    // End of variables declaration//GEN-END:variables
}
